name: CI
on:
  push: { branches: ["**"] }
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest

      - name: Lint (ruff)
        run: ruff . --output-format=github || (echo "::warning::Ruff issues found"; exit 1)

      - name: Milestones freeze check
        run: .github/workflows/check_freeze.sh

      - name: Tests (unit placeholder)
        run: pytest -q

